// ═══════════════════════════════════════════════════════════════════════════
// bo_dau — Chuẩn hóa tiếng Việt để tìm kiếm không dấu.
//
// Mirror web `boDau` (ModuleDuyetBaoGia.tsx): NFD tách dấu, xoá combining
// marks, đổi đ/Đ → d/D, rồi lowercase. Dùng cho search báo giá/LSX.
// ═══════════════════════════════════════════════════════════════════════════

/// Bỏ dấu tiếng Việt + lowercase. "Báo Giá" → "bao gia".
String boDau(String input) {
  if (input.isEmpty) return '';
  final buffer = StringBuffer();
  for (final ch in input.split('')) {
    // Bỏ combining marks (NFD): U+0300–U+036F.
    final code = ch.codeUnitAt(0);
    if (code >= 0x0300 && code <= 0x036F) continue;
    buffer.write(_thay(ch));
  }
  return buffer.toString().toLowerCase();
}

/// Tách dấu bằng cách dùng bảng map ký tự có dấu phổ biến (đ/Đ không bị NFD
/// tách thành base+mark nên phải xử lý riêng).
String _thay(String ch) {
  const map = <String, String>{
    'đ': 'd',
    'Đ': 'D',
    'á': 'a',
    'à': 'a',
    'ả': 'a',
    'ã': 'a',
    'ạ': 'a',
    'ă': 'a',
    'ắ': 'a',
    'ằ': 'a',
    'ẳ': 'a',
    'ẵ': 'a',
    'ặ': 'a',
    'â': 'a',
    'ấ': 'a',
    'ầ': 'a',
    'ẩ': 'a',
    'ẫ': 'a',
    'ậ': 'a',
    'é': 'e',
    'è': 'e',
    'ẻ': 'e',
    'ẽ': 'e',
    'ẹ': 'e',
    'ê': 'e',
    'ế': 'e',
    'ề': 'e',
    'ể': 'e',
    'ễ': 'e',
    'ệ': 'e',
    'í': 'i',
    'ì': 'i',
    'ỉ': 'i',
    'ĩ': 'i',
    'ị': 'i',
    'ó': 'o',
    'ò': 'o',
    'ỏ': 'o',
    'õ': 'o',
    'ọ': 'o',
    'ô': 'o',
    'ố': 'o',
    'ồ': 'o',
    'ổ': 'o',
    'ỗ': 'o',
    'ộ': 'o',
    'ơ': 'o',
    'ớ': 'o',
    'ờ': 'o',
    'ở': 'o',
    'ỡ': 'o',
    'ợ': 'o',
    'ú': 'u',
    'ù': 'u',
    'ủ': 'u',
    'ũ': 'u',
    'ụ': 'u',
    'ư': 'u',
    'ứ': 'u',
    'ừ': 'u',
    'ử': 'u',
    'ữ': 'u',
    'ự': 'u',
    'ý': 'y',
    'ỳ': 'y',
    'ỷ': 'y',
    'ỹ': 'y',
    'ỵ': 'y',
    'Á': 'A',
    'À': 'A',
    'Ả': 'A',
    'Ã': 'A',
    'Ạ': 'A',
    'Ă': 'A',
    'Ắ': 'A',
    'Ằ': 'A',
    'Ẳ': 'A',
    'Ẵ': 'A',
    'Ặ': 'A',
    'Â': 'A',
    'Ấ': 'A',
    'Ầ': 'A',
    'Ẩ': 'A',
    'Ẫ': 'A',
    'Ậ': 'A',
    'É': 'E',
    'È': 'E',
    'Ẻ': 'E',
    'Ẽ': 'E',
    'Ẹ': 'E',
    'Ê': 'E',
    'Ế': 'E',
    'Ề': 'E',
    'Ể': 'E',
    'Ễ': 'E',
    'Ệ': 'E',
    'Í': 'I',
    'Ì': 'I',
    'Ỉ': 'I',
    'Ĩ': 'I',
    'Ị': 'I',
    'Ó': 'O',
    'Ò': 'O',
    'Ỏ': 'O',
    'Õ': 'O',
    'Ọ': 'O',
    'Ô': 'O',
    'Ố': 'O',
    'Ồ': 'O',
    'Ổ': 'O',
    'Ỗ': 'O',
    'Ộ': 'O',
    'Ơ': 'O',
    'Ớ': 'O',
    'Ờ': 'O',
    'Ở': 'O',
    'Ỡ': 'O',
    'Ợ': 'O',
    'Ú': 'U',
    'Ù': 'U',
    'Ủ': 'U',
    'Ũ': 'U',
    'Ụ': 'U',
    'Ư': 'U',
    'Ứ': 'U',
    'Ừ': 'U',
    'Ử': 'U',
    'Ữ': 'U',
    'Ự': 'U',
    'Ý': 'Y',
    'Ỳ': 'Y',
    'Ỷ': 'Y',
    'Ỹ': 'Y',
    'Ỵ': 'Y',
  };
  return map[ch] ?? ch;
}
