export const TECHNICAL_TABLE_MOBILE_LABELS = {
  stage: 'CĐ',
  material: 'VL',
  width: 'Khổ',
  meters: 'TP',
  waste: 'Hao',
  inputMaterial: 'ĐV VL',
  rawMaterialPrice: 'Giá NL',
  doDay: 'Dày',
  cpsx: 'CPSX',
  totalCpsx: 'TT SX',
  materialPrice: 'CPVL',
  totalMaterial: 'TT VL',
  printFilm: 'Màng in',
} as const;
